apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-node-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-node-webhook
subjects:
- kind: ServiceAccount
  name: pod-node-webhook
  namespace: webhook-system 