apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-node-webhook
  namespace: node-restriction
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-node-webhook
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-node-webhook
subjects:
- kind: ServiceAccount
  name: pod-node-webhook
  namespace: node-restriction
roleRef:
  kind: ClusterRole
  name: pod-node-webhook
  apiGroup: rbac.authorization.k8s.io 