apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-node-webhook
webhooks:
- name: pod-node-webhook.node-restriction.svc
  clientConfig:
    service:
      name: pod-node-webhook
      namespace: node-restriction
      path: "/mutate"
      port: 8443
    caBundle: ${CA_BUNDLE}
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations: ["CREATE"]
  failurePolicy: Fail
  sideEffects: None
  admissionReviewVersions: ["v1"] 