apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-node-webhook
webhooks:
- name: pod-node-webhook.example.com
  clientConfig:
    service:
      name: pod-node-webhook
      namespace: webhook-system
      path: "/mutate"
      port: 443
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["pods"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5 